### ISSUE TITLE
SSH asking for a password

### ISSUE THREAD

**Issue by orhun** [Patryk27/kartoffels#35]
I run the command in README.md:

```
$ ssh kartoffels.pwy.io

orhun@kartoffels.pwy.io's password:
orhun@kartoffels.pwy.io: Permission denied (publickey,hostbased,keyboard-interactive).
```

Is there anything else that I need to do? I don't have a custom setting for your domain in `.ssh/config`.

**Comment by Patryk27** [comment]
Interesting, do you have public key generated - i.e. does `~/.ssh/id_rsa` exist on your machine?

**Comment by orhun** [comment]
Nope, I don't have that specific file generated. I have other generated key pairs but `ssh` shouldn't use them as long as they are not configured.

**Comment by Patryk27** [comment]
I see - I think the issue is that russh by default forbids `none` auth; I'll try playing with it tomorrow and ping you back, thanks for reporting!

**Comment by orhun** [comment]
Sounds good, let me know if you need me to test it again :)

And btw, super cool project 🥔

**Comment by Patryk27** [comment]
None-auth should work now - try again and feel free to re-open the issue if something's still wrong 🙂

**Comment by orhun** [comment]
Works like a charm!
