### ISSUE TITLE
Missing atomic instructions

### ISSUE THREAD

**Issue by dbdbc** [Patryk27/kartoffels#43]
The `lr` (e.g. `0x1406a5af`) and `sc` instructions are currently not implemented, causing the following firmware to crash:

```rust
#![no_main]
#![no_std]

use core::sync::atomic::{AtomicU32, Ordering};
use kartoffel;

#[no_mangle]
fn main() {
    AtomicU32::new(5)
        .compare_exchange(5, 10, Ordering::Acquire, Ordering::Relaxed)
        .unwrap();
    loop {}
}
```

I encountered the crash while checking if the embassy-executor could be used for concurrent tasks.

**Comment by Patryk27** [comment]
I've just deployed the newest version - all atomics should be implemented, let me know if something's missing 🙂

**Comment by dbdbc** [comment]
Amazing, thank you. The firmware did no longer crash, and I'm able to use async functions now.
